# Generated by Django 5.0.4 on 2024-04-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
